window.SRPNWorksData = [
  {
    title: "《速背元素周期表40位》",
    author: "Earth-2",
    class: "知识-化学",
    hot: "🔥🔥🔥",
    time: "2022.11.30",
  },
  {
    title: "水循环",
    url: "https://v.douyin.com/CeinsT8D/ 08/01",
    author: "Maugfy",
    class: "知识-地理",
    hot: "🔥🔥🔥",
    time: "2024.10.26",
  },
  {
    title: "海岸地貌",
    url: "https://v.douyin.com/b9eDz9SplFg",
    author: "Maugfy",
    class: "知识-地理",
    hot: "🔥🔥🔥",
    time: "2024.12.13",
  },
  {
    title: '"物理？"',
    url: "https://v.douyin.com/qynZzR1vF-w/",
    author: "Acubens-A",
    class: "知识-物理",
    hot: "🔥🔥🔥",
    time: "2025.01.21",
  },
  {
    title: '"小曲一响，理科登场"',
    url: "https://v.douyin.com/LgB_GJ0mjp4/",
    author: "Acubens-A & Nsakrty",
    class: "知识-数理",
    hot: "🔥🔥🔥",
    time: "2025.03.09",
  },
  {
    title: "地理——我国气候",
    url: "https://v.douyin.com/faiixYBJxBg/",
    author: "水益",
    class: "知识-地理",
    hot: "🔥🔥🔥",
    time: "2025.05.16",
  },
  {
    title: "《⚡️天体物理⚡️》",
    url: "https://v.douyin.com/humgoXBfPjY/",
    author: "天白",
    class: "知识-物理",
    hot: "🔥🔥",
    time: "2024.11.17",
  },
  {
    title: "K型恒星的生命历程 ",
    url: "https://b23.tv/dANYlxz",
    author: "Earth-2",
    class: "知识-天文",
    time: "2021.08.27",
  },
  {
    title: "力学（part 1）",
    url: "https://v.douyin.com/ULix-mH6tJo/",
    author: "XF",
    class: "知识-物理",
    hot: "🔥🔥",
    time: "2025.03.08",
  },
  {
    title: "地球：草",
    url: "https://v.douyin.com/o1TRDDyaX-g/",
    author: "Nsakrty",
    class: "星球-娱乐",
    hot: "🔥🔥",
    time: "2020.12.14",
  },
  {
    title: "SRPN危机",
    url: "https://v.douyin.com/rjnK4cY5yoE/",
    author: "大Q是只屑行星",
    class: "转载",
    time: "2024.06.29",
  },
  {
    title: "土地盐碱化成因",
    url: "https://v.douyin.com/bYnhSkE-QVw/",
    author: "Maugfy",
    class: "知识-地理",
    hot: "🔥🔥🔥",
    time: "2026.01.02",
  },
];